### ISSUE TITLE
.build/ folder is now also considered

### ISSUE THREAD

**Issue by jacquesg** [reneeb/Test-CheckManifest#12]
Seems like the .build directory Dist-Zilla generates is now taken into account when checking for non-manifested files. This only started happening the last day or so:

https://travis-ci.org/jacquesg/p5-Git-Raw/jobs/466892142

**Comment by reneeb** [comment]
Hi,

thanks for filing the bug.

Can you re-run the job? The issue should be fixed in version 1.35 (released about an hour ago)...

Sorry for the inconvenience...

- Renée

**Comment by jacquesg** [comment]
Hi, no problem at all.

Will retest in a bit, will give it some time to index.

**Comment by jacquesg** [comment]
The problem has gone away, thank you!
